### ISSUE TITLE
Do not re-do approval if allowance is less than the staking amount 

### ISSUE THREAD

**Issue by kongliangzhong** [vanmoortel/lrc-staking-dapp#2]
When I want to stake a number greater than the allowance of lrc-staking-contract,  the APPROVAL stepper was skipped, and the staking procedure failed.

**Comment by kongliangzhong** [comment]
I think something is wrong at https://github.com/vanmoortel/lrc-staking-dapp/blob/master/src/components/Action/DepositStepper/logic.js#L13, !!amount should be !amount

**Comment by vanmoortel** [comment]
Thanks you for taking time to submit this issue.
`!!amount` only check that the input of the user is not empty.
The error was on the second part of this condition :
`safeAmount(allowance.value).isGreaterThanOrEqualTo(amount)`
The allowance value is store in redux store as a string of base 10^18 without decimal but the input amount is on base 10 so the condition is always true.
Fixed by using `safeAmount(allowance.value).isGreaterThanOrEqualTo(safeAmountFixed(amount))`.
